### ISSUE TITLE
NoSuchMethod while unit Testing Akka with Testkit

### ISSUE THREAD

**Issue by ImCarrot** [akka/akka#26114]
Hi I am working with `akka 2.5.19`. Below is my `pom.xml` snippet.

    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.12</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.typesafe.akka</groupId>
        <artifactId>akka-testkit_2.11</artifactId>
        <version>2.5.19</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.typesafe.akka</groupId>
        <artifactId>akka-actor_2.11</artifactId>
        <version>2.5.19</version>
    </dependency>
    <dependency>
        <groupId>com.typesafe.akka</groupId>
        <artifactId>akka-stream-kafka_2.12</artifactId>
        <version>1.0-M1</version>
    </dependency>

And I am trying to follow through the [official documentation here](https://doc.akka.io/docs/akka/2.5/testing.html).

If I just copy past the first code snippet from the doc, it gives me the Exception :

> java.lang.NoSuchMethodError: akka.serialization.BaseSerializer.$init$(Lakka/serialization/BaseSerializer;)V

the console out:

    java.lang.NoSuchMethodError: akka.serialization.BaseSerializer.$init$(Lakka/serialization/BaseSerializer;)V

	at akka.stream.serialization.StreamRefSerializer.<init>(StreamRefSerializer.scala:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(ReflectiveDynamicAccess.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(ReflectiveDynamicAccess.scala:39)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(ReflectiveDynamicAccess.scala:39)
	at scala.util.Success.flatMap(Try.scala:231)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:39)
	at akka.serialization.Serialization.serializerOf(Serialization.scala:375)
	at akka.serialization.Serialization$$anonfun$6.apply(Serialization.scala:401)
	at akka.serialization.Serialization$$anonfun$6.apply(Serialization.scala:401)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.immutable.Map$Map4.foreach(Map.scala:188)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
	at akka.serialization.Serialization.<init>(Serialization.scala:401)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:16)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:13)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:962)
	at akka.actor.ActorSystemImpl$$anonfun$loadExtensions$1$1.apply(ActorSystem.scala:995)
	at akka.actor.ActorSystemImpl$$anonfun$loadExtensions$1$1.apply(ActorSystem.scala:993)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:993)
	at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1007)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:882)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:870)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:870)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:891)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:234)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:225)
	at akka.actor.ActorSystem$.create(ActorSystem.scala:160)
	at akka.actor.ActorSystem.create(ActorSystem.scala)
	at TestKitSampleTest.setup(TestKitSampleTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by patriknw** [comment]
Don't mix `_2.11` and `_2.12` artifacts.
akka-stream-kafka_2.12 vs akka-testkit_2.11

I'd recommend using `_2.12` for all of them.

Please close the issue if that is fixing the problem.

**Comment by chbatey** [comment]
Hi @ImCarrot I assume the issue is fixed? Please re-open if not

**Comment by ImCarrot** [comment]
@chbatey  Yes this issue is resolved. The issue was exactly as highlighted by @patriknw in his post
