### PR TITLE
Fix Scala 2.12 compilation error in akka-stream-tests

### PR DESCRIPTION
**Pull request by patriknw**
* immutable.Seq

### CODE REVIEW

**Comment by hepin1989** [comment]
Opps, I foget about that, https://docs.scala-lang.org/overviews/core/collections-migration-213.html
I should have run +test:compile locally.

**Comment by patriknw** [comment]
no worries, we don't compile with 2.12 in PR validation, but it's caught by the nighly CI

**Review by johanandren — APPROVED** [review]
