### ISSUE TITLE
Ambigous reference to overloaded definition when using 2.6.0-M7 with Scala 2.12

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#27735]
I got the following compilation error when using Akka 2.6.0-M7 with Scala 2.12. It compiles with Scala 2.13.

```
[error] both method info in trait Logger of type (x$1: String, x$2: Object*)Unit
[error] and  method info in trait Logger of type (x$1: String, x$2: Any, x$3: Any)Unit
[error] match argument types (String,String,String)
[error]             ctx.log.info("{} {}!", greeting, name)
```

The code looks like:

```scala
Behaviors.receiveMessage {
  case SayHello(name) =>
    ctx.log.info("{} {}!", greeting, name)
    Behaviors.same
  case ChangeGreeting(greet) =>
    behavior(greet)
}
```

**Comment by renatocaval** [comment]
Here is a reproducer: 
https://github.com/renatocaval/akka-logging-bug

I run this compilation using the following:

| Akka version   | Scala version | Results |
|----------------|---------------|---------|
| 2.6.0-M7 | 2.13.0 | success |
| 2.6.0-M7 | 2.12.9 | failure |
| 2.5.25 | 2.13.0 | success |
| 2.5.25 | 2.12.9 | success |

**Comment by raboof** [comment]
Does the classic API have the same problem?

The typed logging API will be replaced with exposing slf4j directly as of https://github.com/akka/akka/pull/27324 (2.6.0-M8)

**Comment by patriknw** [comment]
This is a known problem. Mentioned in upcoming reference docs including workaround via LoggerOps: https://github.com/akka/akka/pull/27696/files#diff-61e32754d42cacc2e7662891eec77e64R85

**Comment by renatocaval** [comment]
Ok, closing this issue then. Thanks.
