### PR TITLE
fix 2.13 compilation error, SortedSet, #26382

### PR DESCRIPTION
**Pull request by patriknw**
and add 2.13.0-M5 to travis build

Refs #26382

### CODE REVIEW

**Review by chbatey — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
Merging since it’s breaking nightlies

**Comment by jrudolph** [comment]
That doesn't compile in Scala 2.12. How did it go through PR validation?

**Comment by patriknw** [comment]
Doh, previous PR https://github.com/akka/akka/pull/26391 passed PR validation although it has compilation error. https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14750/consoleText

```
[error] /localhome/jenkinsakka/workspace/pr-validator-per-commit-jenkins/akka-cluster-tools/src/multi-jvm/scala/akka/cluster/singleton/ClusterSingletonManagerDownedSpec.scala:90:33: value unsorted is not a member of scala.collection.immutable.SortedSet[akka.cluster.Member]
[error]           cluster.state.members.unsorted.map(_.status) should ===(Set(MemberStatus.Up))
[error]                                 ^
```

We must investigate why.

I would also expect that Travis would have failed.
