### ISSUE TITLE
UpgradeToWebSocket  not found in Akka 2.4.2-RC2

### ISSUE THREAD

**Issue by jftregor** [akka/akka#19737]
Hello,

I'm currently working on a project using  Akka 2.4.1 along with akka-http and akka-stream 2.0.3.
This morning, I tried **Akka 2.4.2-RC2**.

This was _almost_ a success :-)

However, I ran into a strange error as the compilation failed like so:
```
[error] /.../src/main/scala/.../server/akkahttp/route/WebSocketRoute.scala:48: not found: type UpgradeToWebsocket
[error]          optionalHeaderValueByType[UpgradeToWebsocket]() {
[error]                                    ^
```
So I tried to add the specific import
```
import akka.http.scaladsl.model.ws._
import akka.http.scaladsl.model.ws.UpgradeToWebSocket
```
but it did not work. Of course, I cleaned the project (several times) and compiled again but the compilation error remains...

The only workaround I found was:
```
// FIXME: following line worked before akka 2.4.2-RC2
// optionalHeaderValueByType[UpgradeToWebsocket]() {
optionalHeaderValueByType[akka.http.scaladsl.model.ws.UpgradeToWebSocket]() {
...
```
BTW, here are the relevant lines from the `build.sbt` file:
```
val akkaVersion = "2.4.2-RC2"

...
libraryDependencies ++= Seq(
    ...		
    	"com.typesafe.akka" %% "akka-stream"             % akkaVersion,
    	"com.typesafe.akka" %% "akka-http-core"          % akkaVersion,
    	"com.typesafe.akka" %% "akka-http-experimental"               % akkaVersion,
    	"com.typesafe.akka" %% "akka-http-spray-json-experimental"    % akkaVersion,
    	"com.typesafe.akka" %% "akka-http-testkit-experimental"       % akkaVersion,
   ...)
```

Am I missing something ?

Regard

**Comment by ktoso** [comment]
`UpgradeToWebSocket` (as such casing is more in line with the WebSocket spec) :wink: 

I recommend using your IDE's find class feature when in trouble like this :)

**Comment by ktoso** [comment]
Actually I'll add a notice of that to the migration guide, thanks for bringing it up!

**Comment by jftregor** [comment]
You're welcome, I can remove my `FIXME` line now :smiley: 

BTW, the same error occurred for _handleWeb**S**ocketMessages_ directive and _isWeb**S**ocketUpgrade_ assertion from http-testkit...

And that's it for me, the project _seems_ to be fully 2.4.2 ready now  :sunglasses:

Regards

**Comment by ktoso** [comment]
Excellent, welcome to 2.4.2 :) Final should be there some time next week, please look forward to it and upgrade once we release :)
