### ISSUE TITLE
Artery exception with Aeron 1.5.2

### ISSUE THREAD

**Issue by guidomedina** [akka/akka#23914]
When I try to upgrade to `Aeron 1.5.2` I get the following exception:
```
java.lang.NoSuchMethodError: io.aeron.Aeron.addPublication(Ljava/lang/String;I)Lio/aeron/Publication;
	at akka.remote.artery.AeronSink$$anon$1.<init>(AeronSink.scala:103) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.remote.artery.AeronSink.createLogicAndMaterializedValue(AeronSink.scala:100) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:627) ~[akka-stream_2.12-2.5.6.jar:?]
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:458) ~[akka-stream_2.12-2.5.6.jar:?]
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:424) ~[akka-stream_2.12-2.5.6.jar:?]
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415) ~[akka-stream_2.12-2.5.6.jar:?]
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:496) ~[akka-stream_2.12-2.5.6.jar:?]
	at akka.remote.artery.Association.runOutboundControlStream(Association.scala:530) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.remote.artery.Association.runOutboundStreams(Association.scala:509) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.remote.artery.Association.associate(Association.scala:502) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.remote.artery.AssociationRegistry.association(Association.scala:763) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.remote.artery.ArteryTransport.association(ArteryTransport.scala:931) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.remote.artery.ArteryTransport.send(ArteryTransport.scala:917) ~[akka-remote_2.12-2.5.6.jar:?]
	at akka.remote.RemoteActorRef.$bang(RemoteActorRefProvider.scala:563) ~[akka-remote_2.12-2.5.6.jar:?]
```

The method `addPublication` is there with the right signature but instead of returning a `Publication` it is now returning a `ConcurrentPublication` which extends `Publication`

**Comment by patriknw** [comment]
Thanks for reporting, but I don't think we can do much about this. Looks like Aeron was changed in a non binary compatible way. Compiling with one method signature and running with another can result in such things.

**Comment by guidomedina** [comment]
I get it, is non-binary compatible for Scala even though it is perfectly legal in the Java world, is there any workaround that could be done? if I knew one I would PR it myself.

**Comment by raboof** [comment]
I'm pretty sure it's not binary compatible in Java either (though it is *source* compatible indeed) - but that might be interesting to double-check and report to Aeron upstream?

**Comment by patriknw** [comment]
we are still compiling with Aeron 1.3. I don't know when they changed, but I wouldn't be surprised if they don't promise any such compatibility. Wire compatibility is probably more important for them.

**Comment by guidomedina** [comment]
@raboof `ConcurrentPublication` is-a `Publication`, in the Java world, `ConcurrentPublication instanceof Publication` is true, that suffice to be binary compatible or legal in Java.

As for wire compatibility I'm not so sure, I think between 1.3 and 1.4 they increased their version number and same between 1.4 to 1.5

**Comment by ktoso** [comment]
It's not just about if something is an instance of, but if a method can be resolved based on the previous compilation result. E.g. the full type signature of a method identifies the target that runtime will then invoke, which we see here that it has changed. So you can't bump Aeron externally, if Akka was compiled against a previous version, since the Akka compiled bytecode is attempting to call methods which don't exist -- you'll have to wait until we compile against 1.5

**Comment by guidomedina** [comment]
I get it, which is a Scala thing (strict signature) and more like `Aeron 1.5.2+`, Artery works fine with `Aeron 1.5.1`

**Comment by guidomedina** [comment]
Alright, closing the issue, as there is nothing that can be done at the moment, itch to be scratched eventually.

**Comment by raboof** [comment]
I wanted to try if Java didn't have the same problem, so I wrote:
```
import io.aeron.Aeron;

class Test {
  public static void main(String[] args) {
    Aeron aeron = Aeron.connect(new Aeron.Context());
    aeron.addPublication("asdf", 42);
  }
}
```

Which compiles with `javac Test.java -cp ~/.ivy2/cache/io.aeron/aeron-client/jars/aeron-client-1.3.0.jar`, but then running it with `java -cp ~/.ivy2/cache/io.aeron/aeron-client/jars/aeron-client-1.3.0.jar:~/Downloads/agrona-0.9.6.jar:. Test` fails before it gets to the `addPublication` part:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/agrona/DirectBuffer
	at Test.main(Test.java:5)
Caused by: java.lang.ClassNotFoundException: org.agrona.DirectBuffer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

Been a while since I ran Java code like this, not sure why it is not seeing `org.argona.DirectBuffer` here...

**Comment by guidomedina** [comment]
Try with Aeron 1.5.1 and then 1.5.2, maybe that will work for your test.

**Comment by raboof** [comment]
Nope same thing - I must be doing something wrong in adding agrona to the classpath but I don't see it right now.

**Comment by guidomedina** [comment]
Agrona 0.9.9 or 0.9.10? try either, not below, maybe that's why.

**Comment by raboof** [comment]
Does that work for you?

**Comment by guidomedina** [comment]
Yeap, I get a runtime exception:
```
Exception in thread "main" io.aeron.exceptions.DriverTimeoutException: CnC file not found: cnc.dat
	at io.aeron.Aeron$Context.connectToDriver(Aeron.java:897)
	at io.aeron.Aeron$Context.conclude(Aeron.java:422)
	at io.aeron.Aeron.<init>(Aeron.java:100)
	at io.aeron.Aeron.connect(Aeron.java:147)
	at com.basho.riak.Test.main(Test.java:7)
```
