### ISSUE TITLE
Websocket example for Java not compiling for high-level routing DSL

### ISSUE THREAD

**Issue by thjaeckle** [akka/akka#18668]
Hi Akka Team.

I am trying to get the Websocket example working with Java 8, Akka 2.4, Akka HTTP 1.0 and this documentation:
http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/java/http/server-side/websocket-support.html

I do one Thing slightly different as in the full Example: I use the high-level routing DSL (also as documented, see below).

Problem is now, that this won't compile:
```
incompatible types: akka.stream.javadsl.Flow<akka.http.javadsl.model.ws.Message,akka.http.javadsl.model.ws.Message,scala.runtime.BoxedUnit> cannot be converted to akka.stream.javadsl.Flow<akka.http.javadsl.model.ws.Message,akka.http.javadsl.model.ws.Message,java.lang.Object>
```
I guess because `akka.http.javadsl.server.directives.WebsocketDirectives#handleWebsocketMessages` takes `Flow[Message, Message, Any]` whereas the non high-level routing DSL `akka.http.javadsl.model.ws.Websocket#handleWebsocketRequestWith` takes `Flow[Message, Message, _]`

The Example with Routing DSL:
```
...
   @Override public Route createRoute() {
      return path("greeter").route(handleWebsocketMessages(greeter()));
   }

   public static Flow<Message, Message, BoxedUnit> greeter() {
        return
            Flow.<Message>create()
                .collect(new JavaPartialFunction<Message, Message>() {
                    @Override
                    public Message apply(Message msg, boolean isCheck) throws Exception {
                        if (isCheck)
                            if (msg.isText()) return null;
                            else throw noMatch();
                        else
                            return handleTextMessage(msg.asTextMessage());
                    }
                });
    }
    public static TextMessage handleTextMessage(TextMessage msg) {
        if (msg.isStrict()) // optimization that directly creates a simple response...
            return TextMessage.create("Hello "+msg.getStrictText());
        else // ... this would suffice to handle all text messages in a streaming fashion
            return TextMessage.create(Source.single("Hello ").concat(msg.getStreamedText()));
    }
...
```

**Comment by thjaeckle** [comment]
Just noticed the Example for Routing:
https://github.com/akka/akka/blob/release-2.3-dev/akka-docs-dev/rst/java/code/docs/http/javadsl/server/WebsocketRoutingExample.java

This also doesn't compile ..

**Comment by jrudolph** [comment]
It compiles in its branch but currently not against the released 1.0 version.

See this commit

https://github.com/akka/akka/commit/e611236435d2a6015eacd79db183db4e14fee8d2

which fixed exactly the problem you are now seeing.

Here's the 1.0 version: https://github.com/akka/akka/blob/4aac6dd7a11c855b53891d5d5c146dae53870f9f/akka-docs-dev/rst/java/code/docs/http/javadsl/server/WebsocketRoutingExample.java

So, this is basically a duplicate of #18028. A new version will soon be released which contains the fix.
