### ISSUE TITLE
Durations add broke scheduler.schedule

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24898]
As reported on gitter by @martin-g

The following code:
```
  scheduler.schedule(
          transferCheckInterval.millis,
          transferCheckInterval.millis,
          () => {
             //  ...
          }
```

Which worked in Akka 2.5.11 breaks in Akka 2.5.12 with the #24646 changes:
```
[error]        (initialDelay: java.time.Duration,interval: java.time.Duration,runnable: Runnable)(implicit executor: scala.concurrent.ExecutionContext)akka.actor.Cancellable <and>
[error]        (initialDelay: scala.concurrent.duration.FiniteDuration,interval: scala.concurrent.duration.FiniteDuration,runnable: Runnable)(implicit executor: scala.concurrent.ExecutionContext)akka.actor.Cancellable
[error]       cannot be applied to (scala.concurrent.duration.FiniteDuration, scala.concurrent.duration.FiniteDuration, () => scala.concurrent.Future[Unit])
[error]      L87:        scheduler.schedule(
[error]      L87:                  ^
```

**Comment by martin-g** [comment]
Scala: 2.12.5
Akka: 2.5.12
SBT 1.1.4, with sbt-errors-summary (0.6.0) plugin

Using `scheduler.schedule(1.millis, 2.millis) {...}` compiles fine but we use the syntax above because this way we can capture the `Runnable` parameter with Mockito in out tests and execute it manually (`capture.getValue().run`)

**Comment by patriknw** [comment]
Ouch, overloading comes with surprises

**Comment by hepin1989** [comment]
@martin-g Sorry for that.

**Comment by patriknw** [comment]
@martin-g I'm trying to reproduce this with the following:
```scala
object SchedulerApiCompileOnlySpec {
  implicit val ec: ExecutionContext = ???
  val scheduler: Scheduler = ???

  scheduler.schedule(10.millis, 10.millis)(println("tick"))
  scheduler.schedule(10.millis, 10.millis, new Runnable {
    override def run(): Unit = println("tick")
  })
  scheduler.schedule(10.millis, 10.millis, () ⇒ {
    println("tick")
  })
}
```


That compiles fine with Scala 2.12, but with 2.11 it has compilation error:
```
cannot be applied to (scala.concurrent.duration.FiniteDuration, scala.concurrent.duration.FiniteDuration, () => Unit)
```
but that is more about that a Scala function `() => Unit` can't be used as a `Runnable` and that isn't changed by the overloads (I tried by removing them).

Can you please share code to reproduce the problem, and confirm that you are using Scala 2.12 including that version of the Akka jars (akka-actor_2.12).

**Comment by martin-g** [comment]
[akka-compilation-issue-24898.zip](https://github.com/akka/akka/files/1941992/akka-compilation-issue-24898.zip)

@patriknw The problematic code is at `src/main/scala/AggregatorActor.scala`. It breaks only if the lambda return a `Future`. Thus the error message `cannot be applied to (scala.concurrent.duration.FiniteDuration, scala.concurrent.duration.FiniteDuration, () => scala.concurrent.Future[Unit])`

**Comment by patriknw** [comment]
@martin-g Thanks. As you probably have figured out the workaround is simple:
```
val r: Runnable = () => scala.concurrent.Future(1)
context.system.scheduler.schedule(1.hour, 1.hour, r)
```

I'm looking into if we can fix this in a better way, but it seems like rather few would be as creative as you to use the `Runnable` in the way you have.
