### PR TITLE
fix akka-cluster-tools compile error

### PR DESCRIPTION
**Pull request by shkoder**
Fixes the below compilation error:
```
akka/akka-cluster-tools/src/multi-jvm/scala/akka/cluster/client/ClusterClientHandoverSpec.scala:43:16: overriding method initialParticipants in trait MultiNodeClusterSpec of type => Int;
[error]  method initialParticipants cannot override final member
[error]   override def initialParticipants: Int = 3
[error]                ^
[error] one error found
```
must have have been introduced with #25201, not sure why it eluded the Jenkins check

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Review by johanandren — APPROVED** [review]
LGTM, thanks!

**Review by chbatey — APPROVED** [review]
LGTM
