### PR TITLE
fix compilation error in multi-jvm tests

### PR DESCRIPTION
**Pull request by patriknw**
* it was not detected by PR validation because of bug
  in sbt 0.13.13, <<= operator with triggeredBy
* updated to sbt 0.13.15

This was not working with sbt 0.13.13:
```
compile in MultiJvm := ((compile in MultiJvm) triggeredBy (compile in Test)).value
```

### CODE REVIEW

**Comment by patriknw** [comment]
PLS BUILD
