### ISSUE TITLE
AbstractFSM.scala doesn't compile with recent Scala 2.13 nightly

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#27410]
this turned up in the Scala 2.13 community build. 

it's reproducible outside dbuild, on Akka's release-2.5 branch, with

```
akka > ++2.13.1-bin-c5eed1d
...
akka > akka-actor/Test/test
[info] Updating akka-actor...
[info] Done updating.
[info] Formatting 2 Java sources ProjectRef(uri("file:/Users/tisue/akka/"), "akka-actor")(compile) ...
[info] Generating 'Tuples.scala'
[info] Generating 'Functions.scala'
[info] Compiling 192 Scala sources and 36 Java sources to /Users/tisue/akka/akka-actor/target/classes ...
[info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.1-bin-c5eed1d. Compiling...
[info]   Compilation completed in 13.747s.
[error] /Users/tisue/akka/akka-actor/src/main/scala/akka/actor/AbstractFSM.scala:175:42: type mismatch;
[error]  found   : x$1.type (with underlying type A1)
[error]  required: S
[error]     super.onTransition(transitionHandler(_: S, _: S))
[error]                                          ^
[error] /Users/tisue/akka/akka-actor/src/main/scala/akka/actor/AbstractFSM.scala:175:48: not found: value x$2
[error]     super.onTransition(transitionHandler(_: S, _: S))
[error]                                                ^
[error] two errors found
[error] (akka-actor / Compile / compileIncremental) Compilation failed
[error] Total time: 43 s, completed Jul 24, 2019 11:48:59 AM
```

can someone from the Akka team advise whether the compiler is actually right here, or whether it's a Scala regression?

/cc @lrytz since we may need to sort this out before we can release Scala 2.13.1

**Comment by lrytz** [comment]
My git bisect script tells me that this changed in https://github.com/scala/scala/pull/8172. @dwijnand do you have time to take a look?

**Comment by dwijnand** [comment]
Minimised https://github.com/scala/scala/compare/2.13.x...dwijnand:pf-from-fn-and-impconvs

**Comment by adriaanm** [comment]
tinier still:

```scala
implicit final def total2pf(fun: (String, String) => Unit): PartialFunction[(String, String), Unit] = ???

val fun: (String, String) => Unit = ???
val pf: PartialFunction[(String, String), Unit] = (a: String, b: String) => fun(a, b)
```

**Comment by SethTisue** [comment]
after scala/scala#8266 was merged, akka went green again in the Scala 2.13 community build
