### ISSUE TITLE
java.lang.NoSuchMethodError: akka.actor.ActorSystem$Settings.HasCluster()Z

### ISSUE THREAD

**Issue by politrons** [akka/akka#28231]
Please use https://discuss.akka.io for questions instead of posting them to the issue tracker.
Hi all,

I´m using Akka stack(Cluster, Http, Stream, Actor) after upgrade from 2.5.16 to 2.6.0 when I create my Avtor System I had an exception since a Method is not there anymore.

```
Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.ActorSystem$Settings.HasCluster()Z
	at akka.remote.RemoteActorRefProvider.<init>(RemoteActorRefProvider.scala:161)
	at akka.cluster.ClusterActorRefProvider.<init>(ClusterActorRefProvider.scala:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:33)
	at scala.util.Try$.apply(Try.scala:209)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$4(ReflectiveDynamicAccess.scala:39)
	at scala.util.Success.flatMap(Try.scala:247)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:39)
	at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:790)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:783)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
```

I clean up all my dependencies to ensure there's no classpath version conflict, no idea what else do. Any suggestion?
